# Generated by Django 5.1.2 on 2026-01-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='Payment_mode',
            new_name='payment_mode',
        ),
    ]
